# master makefile
default:
	@echo Specify what to make:
	@echo " software - make the software "
	@echo “ clean - remove object files”
software: 
	cd src; make software
	
clean: 
	cd src; make clean

cleanall:
	rm FastCycles
	cd src; make clean
